In [1]:
import pandas as pd

### Series: son solo las columnas
### Dataframes: son las matrices o tablas de datos

In [2]:
datos = {"nombre": ["Pedro", "Juan", "Maria"], "edad": [25, 30, 17]}
datos

{'nombre': ['Pedro', 'Juan', 'Maria'], 'edad': [25, 30, 17]}

In [3]:
df = pd.DataFrame(datos)
df

  nombre  edad
0  Pedro    25
1   Juan    30
2  Maria    17

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df["nombre"]

0    Pedro
1     Juan
2    Maria
Name: nombre, dtype: object

In [6]:
df.nombre

0    Pedro
1     Juan
2    Maria
Name: nombre, dtype: object

In [7]:
type(df.nombre)

pandas.core.series.Series

In [8]:
df_empleados = pd.DataFrame({"nombre": ["Ana", "Luis", "Carlos"], "edad": [30, 25, 40]})
print(df_empleados)

   nombre  edad
0     Ana    30
1    Luis    25
2  Carlos    40

In [9]:
edades = df_empleados["edad"]
print(edades)

0    30
1    25
2    40
Name: edad, dtype: int64

In [10]:
type(edades)

pandas.core.series.Series

In [11]:
shape_df = df_empleados.shape
columns_df = df_empleados.columns
index_df = df_empleados.index

In [12]:
print(shape_df)

(3, 2)

In [13]:
print(columns_df)

Index(['nombre', 'edad'], dtype='object')

In [14]:
print(index_df)

RangeIndex(start=0, stop=3, step=1)

## Leer un archivo .csv

In [15]:
df_precipit = pd.read_csv("Precipitaciones.csv")
df_precipit

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7
5,ASTURIAS,196.9,138.4,34.4,73.1,67.4,131.2,22.5,19.2,90.3,74.2,309.8,205.3,1362.7
6,AVILA,67.6,104.5,5.6,83.4,25.7,44.4,5.5,14.2,97.9,91.7,33.9,47.5,621.9
7,BADAJOZ,62.2,78.5,7.7,61.3,13.0,29.6,0.0,2.7,80.5,77.6,10.2,59.3,482.6
8,ILLES BALEARS,81.2,5.3,53.9,22.0,54.4,28.5,8.8,10.0,73.2,55.6,229.9,18.1,640.9
9,BARCELONA,26.8,28.4,16.4,72.2,26.0,42.3,18.7,25.7,76.0,40.6,72.8,2.2,448.1
10,BIZKAIA,175.7,111.5,52.3,57.5,49.1,124.8,37.9,26.4,98.0,53.9,371.4,282.1,1440.6
11,BURGOS,75.8,90.1,17.2,54.2,46.0,75.5,5.8,17.6,48.4,48.7,112.3,88.1,679.7
12,CACERES,70.5,117.3,4.3,95.1,19.5,36.2,0.2,4.9,98.5,130.9,7.1,75.8,660.3
13,CADIZ,148.5,75.4,65.0,35.5,7.5,12.3,0.0,0.1,30.8,24.8,44.5,135.1,579.5
14,CANTABRIA,180.7,112.8,56.0,60.3,60.2,122.9,43.2,30.3,105.1,47.1,384.6,246.6,1449.8
15,CASTELLON,56.6,21.6,30.6,97.3,31.7,46.1,33.9,57.0,106.6,15.3,47.3,4.1,548.1
16,CEUTA,261.9,93.9,209.8,35.4,12.9,2.7,0.0,1.5,7.6,3.7,129.2,61.8,820.4
17,CIUDAD REAL,84.0,39.6,10.3,63.0,11.8,24.0,0.7,16.1,39.8,88.9,23.1,34.2,435.5
18,CORDOBA,88.6,57.5,9.6,64.5,11.6,20.7,0.3,4.7,46.0,48.1,21.0,85.4,458.0
19,CUENCA,93.6,58.4,14.8,84.8,27.0,59.5,9.0,33.4,58.1,99.3,39.5,32.2,609.6
20,GIPUZKOA,173.0,113.6,62.0,62.9,69.0,145.0,46.8,27.0,122.8,69.4,342.0,314.7,1548.2
21,GIRONA,34.9,45.4,16.0,73.2,54.2,39.9,29.4,44.0,89.9,29.6,108.5,12.1,577.1
22,GRANADA,72.2,32.9,17.2,51.0,38.1,15.5,1.3,6.8,11.5,18.6,31.7,25.5,322.3
23,GUADALAJARA,88.4,74.3,15.5,92.7,40.6,66.5,12.3,33.5,76.0,75.4,44.6,35.1,654.9
24,HUELVA,50.7,101.9,35.4,51.5,15.1,14.5,0.0,0.0,78.2,32.0,18.1,105.3,502.7
25,HUESCA,84.3,52.7,5.6,72.7,42.5,71.3,23.6,17.7,78.3,65.0,64.7,59.1,637.5
26,JAEN,100.6,66.8,10.0,53.2,18.5,31.2,0.1,15.8,19.0,45.7,51.0,51.8,463.7
27,LA RIOJA,72.8,54.2,17.6,46.5,47.1,94.8,4.1,16.9,42.0,37.2,115.8,49.7,598.7
28,LAS PALMAS,44.1,32.6,6.1,3.5,0.7,1.1,0.7,1.5,0.9,1.6,10.9,4.5,108.2
29,LEON,92.0,128.2,19.4,56.6,48.9,77.6,6.0,9.2,71.8,60.1,59.8,112.1,741.7
30,LLEIDA,59.3,42.0,12.6,81.7,37.5,66.9,38.6,19.0,55.7,45.0,58.6,32.9,549.8
31,LUGO,179.5,221.7,26.6,79.5,78.4,101.7,13.5,17.6,59.5,111.0,114.1,179.8,1182.9
32,MADRID,69.3,61.7,6.1,77.0,25.7,40.0,5.6,30.0,63.0,84.1,25.2,36.0,523.7
33,MALAGA,139.5,43.7,35.5,56.9,16.5,6.4,0.0,1.2,29.9,13.1,26.5,70.9,440.1
34,MELILLA,44.9,20.0,45.1,57.1,9.0,3.1,0.0,1.2,49.6,1.0,34.1,5.2,270.3
35,MURCIA,44.5,2.3,52.6,61.6,48.7,32.6,9.3,3.3,32.4,20.1,37.4,4.2,349.0
36,NAVARRA,98.8,85.9,23.8,43.7,44.2,87.9,17.6,28.3,64.3,45.0,161.1,186.9,887.5
37,OURENSE,138.9,234.4,10.9,98.8,65.0,86.1,5.5,23.0,65.9,97.5,32.6,144.5,1003.1
38,PALENCIA,52.3,81.3,7.5,55.8,29.7,79.3,3.4,6.8,61.6,47.5,56.0,51.5,532.7
39,PONTEVEDRA,255.4,335.7,22.3,128.4,144.5,80.7,24.6,34.0,92.4,175.7,45.3,236.4,1575.4
40,SALAMANCA,52.9,123.6,4.1,62.4,24.4,50.8,5.6,6.7,85.0,78.6,27.1,48.4,569.6
41,SANTA CRUZ DE TENERIFE,90.6,56.0,20.8,19.4,2.8,3.5,1.7,3.4,3.9,8.2,50.2,25.9,286.4
42,SEGOVIA,63.3,80.5,3.3,88.5,39.8,55.6,6.3,14.4,47.1,62.5,42.9,44.8,549.0
43,SEVILLA,91.1,54.4,24.5,60.7,9.2,8.1,0.1,0.2,46.0,29.9,20.6,114.7,459.5
44,SORIA,75.1,63.5,12.1,67.7,70.7,85.4,10.5,19.4,56.5,47.0,62.9,37.7,608.5
45,TARRAGONA,52.7,28.4,9.7,59.6,19.0,63.8,22.4,43.5,88.7,25.4,115.0,5.1,533.3
46,TERUEL,54.1,28.8,11.9,74.6,48.5,72.6,26.8,48.1,55.0,30.9,60.0,13.2,524.5
47,TOLEDO,83.0,51.1,7.5,62.5,15.0,27.1,3.3,18.6,70.5,94.7,16.4,29.9,479.6
48,VALENCIA,61.9,16.8,49.3,86.4,33.8,34.2,17.1,30.9,99.3,46.1,46.6,5.5,527.9
49,VALLADOLID,29.2,69.1,4.1,65.1,24.3,58.3,1.9,3.8,54.1,40.2,41.7,35.9,427.7
50,ZAMORA,53.0,112.0,6.8,63.7,19.8,54.2,3.1,9.6,78.5,55.3,29.0,50.3,535.3
51,ZARAGOZA,52.0,30.0,3.6,52.7,38.3,57.5,13.5,13.2,61.5,27.4,76.6,23.4,449.7

In [16]:
type(df_precipit)

pandas.core.frame.DataFrame

In [17]:
df_precipit.head()

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7

In [18]:
df_precipit.head(2)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5

In [19]:
df_precipit.tail()

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
47,TOLEDO,83.0,51.1,7.5,62.5,15.0,27.1,3.3,18.6,70.5,94.7,16.4,29.9,479.6
48,VALENCIA,61.9,16.8,49.3,86.4,33.8,34.2,17.1,30.9,99.3,46.1,46.6,5.5,527.9
49,VALLADOLID,29.2,69.1,4.1,65.1,24.3,58.3,1.9,3.8,54.1,40.2,41.7,35.9,427.7
50,ZAMORA,53.0,112.0,6.8,63.7,19.8,54.2,3.1,9.6,78.5,55.3,29.0,50.3,535.3
51,ZARAGOZA,52.0,30.0,3.6,52.7,38.3,57.5,13.5,13.2,61.5,27.4,76.6,23.4,449.7

In [20]:
df_precipit.shape

(52, 14)

In [21]:
df_precipit.columns

Index(['region', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
       'anual'],
      dtype='object')

In [22]:
df_precipit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      52 non-null     object
 1   enero       52 non-null     float64
 2   febrero     52 non-null     float64
 3   marzo       52 non-null     float64
 4   abril       52 non-null     float64
 5   mayo        52 non-null     float64
 6   junio       52 non-null     float64
 7   julio       52 non-null     float64
 8   agosto      52 non-null     float64
 9   septiembre  52 non-null     float64
 10  octubre     52 non-null     float64
 11  noviembre   52 non-null     float64
 12  diciembre   52 non-null     float64
 13  anual       52 non-null     float64
dtypes: float64(13), object(1)
memory usage: 5.8+ KB

In [23]:
df_precipit.describe()

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,92.996154,78.632692,26.684615,64.500000,38.305769,54.182692,11.840385,17.178846,62.246154,54.373077,82.494231,76.192308,659.626923
std,57.127171,67.454280,31.473913,21.421942,29.079576,36.821635,13.256390,13.939496,28.581205,36.619785,91.689789,80.409042,352.905548
min,26.800000,2.300000,3.300000,3.500000,0.700000,1.100000,0.000000,0.000000,0.900000,1.000000,7.100000,1.800000,108.200000
25%,53.825000,32.825000,9.125000,53.950000,18.875000,26.325000,1.600000,4.850000,46.000000,29.825000,32.375000,22.075000,455.925000
50%,73.950000,62.600000,17.200000,62.700000,35.650000,50.400000,6.150000,16.500000,62.300000,46.550000,46.950000,47.950000,548.550000
75%,97.300000,102.550000,35.425000,77.625000,48.750000,78.025000,17.875000,26.550000,81.625000,74.500000,102.725000,107.000000,665.150000
max,261.900000,335.700000,209.800000,128.400000,149.500000,145.000000,46.800000,57.000000,122.800000,175.700000,384.600000,314.700000,1575.400000

In [24]:
df_precipit.head(5)

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7

In [25]:
serie_preci = df_precipit["region"]
serie_preci

0                   A CORUNA
1                   ALBACETE
2                   ALICANTE
3                    ALMERIA
4                      ARABA
5                   ASTURIAS
6                      AVILA
7                    BADAJOZ
8              ILLES BALEARS
9                  BARCELONA
10                   BIZKAIA
11                    BURGOS
12                   CACERES
13                     CADIZ
14                 CANTABRIA
15                 CASTELLON
16                     CEUTA
17               CIUDAD REAL
18                   CORDOBA
19                    CUENCA
20                  GIPUZKOA
21                    GIRONA
22                   GRANADA
23               GUADALAJARA
24                    HUELVA
25                    HUESCA
26                      JAEN
27                  LA RIOJA
28                LAS PALMAS
29                      LEON
30                    LLEIDA
31                      LUGO
32                    MADRID
33                    MALAGA
34                   MELILLA
35                    MURCIA
36                   NAVARRA
37                   OURENSE
38                  PALENCIA
39                PONTEVEDRA
40                 SALAMANCA
41    SANTA CRUZ DE TENERIFE
42                   SEGOVIA
43                   SEVILLA
44                     SORIA
45                 TARRAGONA
46                    TERUEL
47                    TOLEDO
48                  VALENCIA
49                VALLADOLID
50                    ZAMORA
51                  ZARAGOZA
Name: region, dtype: object

In [26]:
datos = [10, 20, 30, 40, 50]
datos

[10, 20, 30, 40, 50]

In [27]:
series2 = pd.Series(datos)
series2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
indices = ['a', 'b', 'c', 'd', 'e']
series2 = pd.Series(datos, indices)
series2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [29]:
series2['b']

np.int64(20)

In [30]:
type(series2)

pandas.core.series.Series

In [31]:
type(series2['b'])

numpy.int64

In [32]:
capitales = {'col':'bog', 'arg': 'bno', 'fr':'par'}
capitales

{'col': 'bog', 'arg': 'bno', 'fr': 'par'}

In [33]:
series3 = pd.Series(capitales)
series3

col    bog
arg    bno
fr     par
dtype: object

In [34]:
series3['col']

'bog'

In [35]:
datos2 = [10, 20, 30, 40]
indices2 = ['a', 'b', 'c', 'd']
serie_con_indices = pd.Series(datos2, indices2)
valor_c = serie_con_indices['c']

def imprimir_valor_c(dato):
    print(dato)
    
imprimir_valor_c(valor_c)

30

In [36]:
serie_desde_diccionario = {'a': 30, 'b': 70, 'c': 160, 'd': 50}
suma_ad = pd.Series(serie_desde_diccionario['a'] + serie_desde_diccionario['d'])

def imprimir_suma_ad():
    print(suma_ad)
    
imprimir_suma_ad()

0    80
dtype: int64

In [37]:
serie_num = pd.Series(datos)
serie_num

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [38]:
serie_num[0] = serie_num[0] + 10
serie_num

0    20
1    20
2    30
3    40
4    50
dtype: int64

In [39]:
serie_num = serie_num + 10
serie_num

0    30
1    30
2    40
3    50
4    60
dtype: int64

In [40]:
serie_num = serie_num * 5
serie_num

0    150
1    150
2    200
3    250
4    300
dtype: int64

## Limpiar los datos para poder usarlos
### que existan errores, falten datos, formatos incorrectos, eliminar duplicados

In [41]:
productos = {"id_producto": [1001, 1002, 1003, 1003],
        "cantidad_vendida": [30, None, 25, 25],
        "precio": [20.5, 15.5, None, 22.5]}
productos

{'id_producto': [1001, 1002, 1003, 1003],
 'cantidad_vendida': [30, None, 25, 25],
 'precio': [20.5, 15.5, None, 22.5]}

In [42]:
productos_df = pd.DataFrame(productos)
productos_df

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
1         1002               NaN    15.5
2         1003              25.0     NaN
3         1003              25.0    22.5

In [43]:
productos_df.head()

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
1         1002               NaN    15.5
2         1003              25.0     NaN
3         1003              25.0    22.5

In [44]:
productos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_producto       4 non-null      int64
 1   cantidad_vendida  3 non-null      float64
 2   precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [45]:
productos_df.isnull() # indica un true donde el valor es nulo

   id_producto  cantidad_vendida  precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [46]:
productos_df.isnull().sum()

id_producto         0
cantidad_vendida    1
precio              1
dtype: int64

In [47]:
# conociendo donde estan los valores faltantes, se toma una decision segun el caso
# dependiendo, se pueden eliminar pero se sabe que afecta las estadisticas,
# quizas sea en ocasiones cambiarlo por otro tipo de valores como puede ser la media

# Caso Eliminar:
df_eliminados = productos_df.dropna()
df_eliminados

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
3         1003              25.0    22.5

In [48]:
# Caso Cambiar Valores por Otros
valores_nuevos = {'cantidad_vendida': 0, 'precio': productos_df["precio"].mean()}
df_rellenados = productos_df.fillna(valores_nuevos)
df_rellenados

   id_producto  cantidad_vendida  precio
0         1001              30.0    20.5
1         1002               0.0    15.5
2         1003              25.0    19.5
3         1003              25.0    22.5

In [49]:
# cambiar los tipos de datos al correcto, en este caso pasa de float a entero en cantidad vendida
df_rellenados["cantidad_vendida"] = df_rellenados["cantidad_vendida"].astype(int)
df_rellenados

   id_producto  cantidad_vendida  precio
0         1001                30    20.5
1         1002                 0    15.5
2         1003                25    19.5
3         1003                25    22.5

In [50]:
# Verificar si hay duplicados y tomar decisiones con relacion a ello, si dejarlos o eliminarlos o sumarlos
df_unicos = df_rellenados.drop_duplicates() # compara que las filas sean completamente iguales para eliminar
df_unicos

   id_producto  cantidad_vendida  precio
0         1001                30    20.5
1         1002                 0    15.5
2         1003                25    19.5
3         1003                25    22.5

In [51]:
# no elimino nada porque no habian filas identicas
df_unicos = df_rellenados.drop_duplicates(subset= ["id_producto"]) # se eliminan las filas que tienen datos duplicados
df_unicos

   id_producto  cantidad_vendida  precio
0         1001                30    20.5
1         1002                 0    15.5
2         1003                25    19.5

In [52]:
# El conjunto de datos proporcionado tiene algunas entradas duplicadas.
data = {
    'ID': [1, 2, 3, 4, 1],
    'Producto': ['Producto A', 'Producto B', 'Producto C', 'Producto D', 'Producto A'],
    'Cantidad': [10, 20, 30, 40, 50],
    'Precio': [100, 200, 300, 400, 100]
}

res = pd.DataFrame(data)
res

   ID    Producto  Cantidad  Precio
0   1  Producto A        10     100
1   2  Producto B        20     200
2   3  Producto C        30     300
3   4  Producto D        40     400
4   1  Producto A        50     100

In [53]:
res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        5 non-null      int64
 1   Producto  5 non-null      object
 2   Cantidad  5 non-null      int64
 3   Precio    5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [54]:
df_sin_duplicados = res.drop_duplicates("ID")
df_sin_duplicados

   ID    Producto  Cantidad  Precio
0   1  Producto A        10     100
1   2  Producto B        20     200
2   3  Producto C        30     300
3   4  Producto D        40     400

In [55]:
# Tu tabla de ventas, la columna "Precio" tiene algunos valores nulos.
data = {
    'ID': [1, 2, 3, 4],
    'Producto': ['Producto A', 'Producto B', 'Producto C', 'Producto D'],
    'Cantidad': [10, 20, 30, 40],
    'Precio': [100, None, 300, None]
}

res = pd.DataFrame(data)
res

   ID    Producto  Cantidad  Precio
0   1  Producto A        10   100.0
1   2  Producto B        20     NaN
2   3  Producto C        30   300.0
3   4  Producto D        40     NaN

In [56]:
res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        4 non-null      int64
 1   Producto  4 non-null      object
 2   Cantidad  4 non-null      int64
 3   Precio    2 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes

In [57]:
values = {"Precio": res["Precio"].mean()}
res = res.fillna(values)
res

   ID    Producto  Cantidad  Precio
0   1  Producto A        10   100.0
1   2  Producto B        20   200.0
2   3  Producto C        30   300.0
3   4  Producto D        40   200.0

In [58]:
# aplicar filtros a series
datos2 = pd.Series(datos2)
filtro = datos2 > 10
filtro

0    False
1     True
2     True
3     True
dtype: bool

In [59]:
serie_filtrada = datos2[filtro]
serie_filtrada

1    20
2    30
3    40
dtype: int64

In [60]:
mayores = res[res['Cantidad'] > 20]
mayores

   ID    Producto  Cantidad  Precio
2   3  Producto C        30   300.0
3   4  Producto D        40   200.0

In [61]:
datos3 = pd.Series(["banano", "manzana", "pera", "papaya"])
datos3

0     banano
1    manzana
2       pera
3     papaya
dtype: object

In [62]:
type(datos3[0])

str

In [63]:
# filtrar todos los que tienen la letra p en su nombre, el filtro se aplica no al objeto str sino al serie
print(dir(datos3)) # imprimir todos los metodos de la clase Serie

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'str', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

In [64]:
help(datos3.str)

Help on StringMethods in module pandas.core.strings.accessor object:

class StringMethods(pandas.core.base.NoNewAttributesMixin)
 |  StringMethods(data) -> 'None'
 |
 |  Vectorized string functions for Series and Index.
 |
 |  NAs stay NA unless handled otherwise by a particular method.
 |  Patterned after Python's string methods, with some inspiration from
 |  R's stringr package.
 |
 |  Examples
 |  --------
 |  >>> s = pd.Series(["A_Str_Series"])
 |  >>> s
 |  0    A_Str_Series
 |  dtype: object
 |
 |  >>> s.str.split("_")
 |  0    [A, Str, Series]
 |  dtype: object
 |
 |  >>> s.str.replace("_", "")
 |  0    AStrSeries
 |  dtype: object
 |
 |  Method resolution order:
 |      StringMethods
 |      pandas.core.base.NoNewAttributesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __getitem__(self, key)
 |
 |  __init__(self, data) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self) -> 'Iterator'
 |
 |  capitalize(self)
 |      Convert strings in the Series/Index to be capitalized.
 |
 |      Equivalent to :meth:`str.capitalize`.
 |
 |      Returns
 |      -------
 |      Series or Index of object
 |
 |      See Also
 |      --------
 |      Series.str.lower : Converts all characters to lowercase.
 |      Series.str.upper : Converts all characters to uppercase.
 |      Series.str.title : Converts first character of each word to uppercase and
 |          remaining to lowercase.
 |      Series.str.capitalize : Converts first character to uppercase and
 |          remaining to lowercase.
 |      Series.str.swapcase : Converts uppercase to lowercase and lowercase to
 |          uppercase.
 |      Series.str.casefold: Removes all case distinctions in the string.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['lower', 'CAPITALS', 'this is a sentence', 'SwApCaSe'])
 |      >>> s
 |      0                 lower
 |      1              CAPITALS
 |      2    this is a sentence
 |      3              SwApCaSe
 |      dtype: object
 |
 |      >>> s.str.lower()
 |      0                 lower
 |      1              capitals
 |      2    this is a sentence
 |      3              swapcase
 |      dtype: object
 |
 |      >>> s.str.upper()
 |      0                 LOWER
 |      1              CAPITALS
 |      2    THIS IS A SENTENCE
 |      3              SWAPCASE
 |      dtype: object
 |
 |      >>> s.str.title()
 |      0                 Lower
 |      1              Capitals
 |      2    This Is A Sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.capitalize()
 |      0                 Lower
 |      1              Capitals
 |      2    This is a sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.swapcase()
 |      0                 LOWER
 |      1              capitals
 |      2    THIS IS A SENTENCE
 |      3              sWaPcAsE
 |      dtype: object
 |
 |  casefold(self)
 |      Convert strings in the Series/Index to be casefolded.
 |
 |      Equivalent to :meth:`str.casefold`.
 |
 |      Returns
 |      -------
 |      Series or Index of object
 |
 |      See Also
 |      --------
 |      Series.str.lower : Converts all characters to lowercase.
 |      Series.str.upper : Converts all characters to uppercase.
 |      Series.str.title : Converts first character of each word to uppercase and
 |          remaining to lowercase.
 |      Series.str.capitalize : Converts first character to uppercase and
 |          remaining to lowercase.
 |      Series.str.swapcase : Converts uppercase to lowercase and lowercase to
 |          uppercase.
 |      Series.str.casefold: Removes all case distinctions in the string.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['lower', 'CAPITALS', 'this is a sentence', 'SwApCaSe'])
 |      >>> s
 |      0                 lower
 |      1              CAPITALS
 |      2    this is a sentence
 |      3              SwApCaSe
 |      dtype: object
 |
 |      >>> s.str.lower()
 |      0                 lower
 |      1              capitals
 |      2    this is a sentence
 |      3              swapcase
 |      dtype: object
 |
 |      >>> s.str.upper()
 |      0                 LOWER
 |      1              CAPITALS
 |      2    THIS IS A SENTENCE
 |      3              SWAPCASE
 |      dtype: object
 |
 |      >>> s.str.title()
 |      0                 Lower
 |      1              Capitals
 |      2    This Is A Sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.capitalize()
 |      0                 Lower
 |      1              Capitals
 |      2    This is a sentence
 |      3              Swapcase
 |      dtype: object
 |
 |      >>> s.str.swapcase()
 |      0                 LOWER
 |      1              capitals
 |      2    THIS IS A SENTENCE
 |      3              sWaPcAsE
 |      dtype: object
 |
 |  cat(self, others=None, sep: 'str | None' = None, na_rep=None, join: 'AlignJoin' = 'left') -> 'str | Series | Index'
 |      Concatenate strings in the Series/Index with given separator.
 |
 |      If `others` is specified, this function concatenates the Series/Index
 |      and elements of `others` element-wise.
 |      If `others` is not passed, then all values in the Series/Index are
 |      concatenated into a single string with a given `sep`.
 |
 |      Parameters
 |      ----------
 |      others : Series, Index, DataFrame, np.ndarray or list-like
 |          Series, Index, DataFrame, np.ndarray (one- or two-dimensional) and
 |          other list-likes of strings must have the same length as the
 |          calling Series/Index, with the exception of indexed objects (i.e.
 |          Series/Index/DataFrame) if `join` is not None.
 |
 |          If others is a list-like that contains a combination of Series,
 |          Index or np.ndarray (1-dim), then all elements will be unpacked and
 |          must satisfy the above criteria individually.
 |
 |          If others is None, the method returns the concatenation of all
 |          strings in the calling Series/Index.
 |      sep : str, default ''
 |          The separator between the different elements/columns. By default
 |          the empty string `''` is used.
 |      na_rep : str or None, default None
 |          Representation that is inserted for all missing values:
 |
 |          - If `na_rep` is None, and `others` is None, missing values in the
 |            Series/Index are omitted from the result.
 |          - If `na_rep` is None, and `others` is not None, a row containing a
 |            missing value in any of the columns (before concatenation) will
 |            have a missing value in the result.
 |      join : {'left', 'right', 'outer', 'inner'}, default 'left'
 |          Determines the join-style between the calling Series/Index and any
 |          Series/Index/DataFrame in `others` (objects without an index need
 |          to match the length of the calling Series/Index). To disable
 |          alignment, use `.values` on any Series/Index/DataFrame in `others`.
 |
 |      Returns
 |      -------
 |      str, Series or Index
 |          If `others` is None, `str` is returned, otherwise a `Series/Index`
 |          (same type as caller) of objects is returned.
 |
 |      See Also
 |      --------
 |      split : Split each string in the Series/Index.
 |      join : Join lists contained as elements in the Series/Index.
 |
 |      Examples
 |      --------
 |      When not passing `others`, all values are concatenated into a single
 |      string:
 |
 |      >>> s = pd.Series(['a', 'b', np.nan, 'd'])
 |      >>> s.str.cat(sep=' ')
 |      'a b d'
 |
 |      By default, NA values in the Series are ignored. Using `na_rep`, they
 |      can be given a representation:
 |
 |      >>> s.str.cat(sep=' ', na_rep='?')
 |      'a b ? d'
 |
 |      If `others` is specified, corresponding values are concatenated with
 |      the separator. Result will be a Series of strings.
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], sep=',')
 |      0    a,A
 |      1    b,B
 |      2    NaN
 |      3    d,D
 |      dtype: object
 |
 |      Missing values will remain missing in the result, but can again be
 |      represented using `na_rep`
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], sep=',', na_rep='-')
 |      0    a,A
 |      1    b,B
 |      2    -,C
 |      3    d,D
 |      dtype: object
 |
 |      If `sep` is not specified, the values are concatenated without
 |      separation.
 |
 |      >>> s.str.cat(['A', 'B', 'C', 'D'], na_rep='-')
 |      0    aA
 |      1    bB
 |      2    -C
 |      3    dD
 |      dtype: object
 |
 |      Series with different indexes can be aligned before concatenation. The
 |      `join`-keyword works as in other methods.
 |
 |      >>> t = pd.Series(['d', 'a', 'e', 'c'], index=[3, 0, 4, 2])
 |      >>> s.str.cat(t, join='left', na_rep='-')
 |      0    aa
 |      1    b-
 |      2    -c
 |      3    dd
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='outer', na_rep='-')
 |      0    aa
 |      1    b-
 |      2    -c
 |      3    dd
 |      4    -e
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='inner', na_rep='-')
 |      0    aa
 |      2    -c
 |      3    dd
 |      dtype: object
 |      >>>
 |      >>> s.str.cat(t, join='right', na_rep='-')
 |      3    dd
 |      0    aa
 |      4    -e
 |      2    -c
 |      dtype: object
 |
 |      For more examples, see :ref:`here <text.concatenate>`.
 |
 |  center(self, width: 'int', fillchar: 'str' = ' ')
 |      Pad left and right side of strings in the Series/Index.
 |
 |      Equivalent to :meth:`str.center`.
 |
 |      Parameters
 |      ----------
 |      width : int
 |          Minimum width of resulting string; additional characters will be filled
 |          with ``fillchar``.
 |      fillchar : str
 |          Additional character for filling, default is whitespace.
 |
 |      Returns
 |      -------
 |      Series/Index of objects.
 |
 |      Examples
 |      --------
 |      For Series.str.center:
 |
 |      >>> ser = pd.Series(['dog', 'bird', 'mouse'])
 |      >>> ser.str.center(8, fillchar='.')
 |      0   ..dog...
 |      1   ..bird..
 |      2   .mouse..
 |      dtype: object
 |
 |      For Series.str.ljust:
 |
 |      >>> ser = pd.Series(['dog', 'bird', 'mouse'])
 |      >>> ser.str.ljust(8, fillchar='.')
 |      0   dog.....
 |      1   bird....
 |      2   mouse...
 |      dtype: object
 |
 |      For Series.str.rjust:
 |
 |      >>> ser = pd.Series(['dog', 'bird', 'mouse'])
 |      >>> ser.str.rjust(8, fillchar='.')
 |      0   .....dog
 |      1   ....bird
 |      2   ...mouse
 |      dtype: object
 |
 |  contains(self, pat, case: 'bool' = True, flags: 'int' = 0, na=<no_default>, regex: 'bool' = True)
 |      Test if pattern or regex is contained within a string of a Series or Index.
 |
 |      Return boolean Series or Index based on whether a given pattern or regex is
 |      contained within a string of a Series or Index.
 |
 |      Parameters
 |      ----------
 |      pat : str
 |          Character sequence or regular expression.
 |      case : bool, default True
 |          If True, case sensitive.
 |      flags : int, default 0 (no flags)
 |          Flags to pass through to the re module, e.g. re.IGNORECASE.
 |      na : scalar, optional
 |          Fill value for missing values. The default depends on dtype of the
 |          array. For object-dtype, ``numpy.nan`` is used. For the nullable
 |          ``StringDtype``, ``pandas.NA`` is used. For the ``"str"`` dtype,
 |          ``False`` is used.
 |      regex : bool, default True
 |          If True, assumes the pat is a regular expression.
 |
 |          If False, treats the pat as a literal string.
 |
 |      Returns
 |      -------
 |      Series or Index of boolean values
 |          A Series or Index of boolean values indicating whether the
 |          given pattern is contained within the string of each element
 |          of the Series or Index.
 |
 |      See Also
 |      --------
 |      match : Analogous, but stricter, relying on re.match instead of re.search.
 |      Series.str.startswith : Test if the start of each string element matches a
 |          pattern.
 |      Series.str.endswith : Same as startswith, but tests the end of string.
 |
 |      Examples
 |      --------
 |      Returning a Series of booleans using only a literal pattern.
 |
 |      >>> s1 = pd.Series(['Mouse', 'dog', 'house and parrot', '23', np.nan])
 |      >>> s1.str.contains('og', regex=False)
 |      0    False
 |      1     True
 |      2    False
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Returning an Index of booleans using only a literal pattern.
 |
 |      >>> ind = pd.Index(['Mouse', 'dog', 'house and parrot', '23.0', np.nan])
 |      >>> ind.str.contains('23', regex=False)
 |      Index([False, False, False, True, nan], dtype='object')
 |
 |      Specifying case sensitivity using `case`.
 |
 |      >>> s1.str.contains('oG', case=True, regex=True)
 |      0    False
 |      1    False
 |      2    False
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Specifying `na` to be `False` instead of `NaN` replaces NaN values
 |      with `False`. If Series or Index does not contain NaN values
 |      the resultant dtype will be `bool`, otherwise, an `object` dtype.
 |
 |      >>> s1.str.contains('og', na=False, regex=True)
 |      0    False
 |      1     True
 |      2    False
 |      3    False
 |      4    False
 |      dtype: bool
 |
 |      Returning 'house' or 'dog' when either expression occurs in a string.
 |
 |      >>> s1.str.contains('house|dog', regex=True)
 |      0    False
 |      1     True
 |      2     True
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Ignoring case sensitivity using `flags` with regex.
 |
 |      >>> import re
 |      >>> s1.str.contains('PARROT', flags=re.IGNORECASE, regex=True)
 |      0    False
 |      1    False
 |      2     True
 |      3    False
 |      4      NaN
 |      dtype: object
 |
 |      Returning any digit using regular expression.
 |
 |      >>> s1.str.contains('\\d', regex=True)
 |      0    False
 |      1    False
 |      2    False
 |      3     True
 |      4      NaN
 |      dtype: object
 |
 |      Ensure `pat` is a not a literal pattern when `regex` is set to True.
 |      Note in the following example one might expect only `s2[1]` and `s2[3]` to
 |      return `True`. However, '.0' as a regex matches any character
 |      followed by a 0.
 |
 |      >>> s2 = pd.Series(['40', '40.0', '41', '41.0', '35'])
 |      >>> s2.str.contains('.0', regex=True)
 |      0     True
 |      1     True
 |      2    False
 |      3     True
 |      4    False
 |      dtype: bool
 |
 |  count(self, pat, flags: 'int' = 0)
 |      Count occurrences of pattern in each string of the Series/Index.
 |
 |      This function is used to count the number of times a particular regex
 |      pattern is repeated in each of the string elements of the
 |      :class:`~pandas.Series`.
 |
 |      Parameters
 |      ----------
 |      pat : str
 |          Valid regular expression.
 |      flags : int, default 0, meaning no flags
 |          Flags for the `re` module. For a complete list, `see here
 |          <https://docs.python.org/3/howto/regex.html#compilation-flags>`_.
 |      **kwargs
 |          For compatibility with other string methods. Not used.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Same type as the calling object containing the integer counts.
 |
 |      See Also
 |      --------
 |      re : Standard library module for regular expressions.
 |      str.count : Standard library version, without regular expression support.
 |
 |      Notes
 |      -----
 |      Some characters need to be escaped when passing in `pat`.
 |      eg. ``'$'`` has a special meaning in regex and must be escaped when
 |      finding this literal character.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['A', 'B', 'Aaba', 'Baca', np.nan, 'CABA', 'cat'])
 |      >>> s.str.count('a')
 |      0    0.0
 |      1    0.0
 |      2    2.0
 |      3    2.0
 |      4    NaN
 |      5    0.0
 |      6    1.0
 |      dtype: float64
 |
 |      Escape ``'$'`` to find the literal dollar sign.
 |
 |      >>> s = pd.Series(['$', 'B', 'Aab$', '$$ca', 'C$B$', 'cat'])
 |      >>> s.str.count('\\$')
 |      0    1
 |      1    0
 |      2    1
 |      3    2
 |      4    2
 |      5    0
 |      dtype: int64
 |
 |      This is also available on Index
 |
 |      >>> pd.Index(['A', 'A', 'Aaba', 'cat']).str.count('a')
 |      Index([0, 0, 2, 1], dtype='int64')
 |
 |  decode(self, encoding, errors: 'str' = 'strict', dtype: 'str | DtypeObj | None' = None)
 |      Decode character string in the Series/Index using indicated encoding.
 |
 |      Equivalent to :meth:`str.decode` in python2 and :meth:`bytes.decode` in
 |      python3.
 |
 |      Parameters
 |      ----------
 |      encoding : str
 |      errors : str, optional
 |          Specifies the error handling scheme.
 |          Possible values are those supported by :meth:`bytes.decode`.
 |      dtype : str or dtype, optional
 |          The dtype of the result. When not ``None``, must be either a string or
 |          object dtype. When ``None``, the dtype of the result is determined by
 |          ``pd.options.future.infer_string``.
 |
 |          .. versionadded:: 2.3.0
 |
 |      Returns
 |      -------
 |      Series or Index
 |
 |      Examples
 |      --------
 |      For Series:
 |
 |      >>> ser = pd.Series([b'cow', b'123', b'()'])
 |      >>> ser.str.decode('ascii')
 |      0   cow
 |      1   123
 |      2   ()
 |      dtype: object
 |
 |  encode(self, encoding, errors: 'str' = 'strict')
 |      Encode character string in the Series/Index using indicated encoding.
 |
 |      Equivalent to :meth:`str.encode`.
 |
 |      Parameters
 |      ----------
 |      encoding : str
 |      errors : str, optional
 |
 |      Returns
 |      -------
 |      Series/Index of objects
 |
 |      Examples
 |      --------
 |      >>> ser = pd.Series(['cow', '123', '()'])
 |      >>> ser.str.encode(encoding='ascii')
 |      0     b'cow'
 |      1     b'123'
 |      2      b'()'
 |      dtype: object
 |
 |  endswith(self, pat: 'str | tuple[str, ...]', na: 'Scalar | lib.NoDefault' = <no_default>) -> 'Series | Index'
 |      Test if the end of each string element matches a pattern.
 |
 |      Equivalent to :meth:`str.endswith`.
 |
 |      Parameters
 |      ----------
 |      pat : str or tuple[str, ...]
 |          Character sequence or tuple of strings. Regular expressions are not
 |          accepted.
 |      na : scalar, optional
 |          Object shown if element tested is not a string. The default depends
 |          on dtype of the array. For object-dtype, ``numpy.nan`` is used.
 |          For the nullable ``StringDtype``, ``pandas.NA`` is used.
 |          For the ``"str"`` dtype, ``False`` is used.
 |
 |      Returns
 |      -------
 |      Series or Index of bool
 |          A Series of booleans indicating whether the given pattern matches
 |          the end of each string element.
 |
 |      See Also
 |      --------
 |      str.endswith : Python standard library string method.
 |      Series.str.startswith : Same as endswith, but tests the start of string.
 |      Series.str.contains : Tests if string element contains a pattern.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(['bat', 'bear', 'caT', np.nan])
 |      >>> s
 |      0     bat
 |      1    bear
 |      2     caT
 |      3     NaN
 |      dtype: object
 |
 |      >>> s.str.endswith('t')
 |      0     True
 |      1    False
 |      2    False
 |      3      NaN
 |      dtype: object
 |
 |      >>> s.str.endswith(('t', 'T'))
 |      0     True
 |      1    False
 |      2     True
 |      3      NaN
 |      dtype: object
 |

In [65]:
filtro2 = datos3.str.contains("p")
filtro2

0    False
1    False
2     True
3     True
dtype: bool

In [66]:
datos3[filtro2]

2      pera
3    papaya
dtype: object

In [67]:
serie_numeros = pd.Series(range(1, 21))
filtro = serie_numeros > 10
serie_numeros[filtro]

10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
dtype: int64

In [68]:
valores = pd.Series([18, 22, 7, 9, 15, 8])

filtro = valores % 2 == 0
valores[filtro]

0    18
1    22
5     8
dtype: int64

## Agregacion

### Resume los datos, combina varios datos como puede ser un promedio o una suma

In [69]:
promedio = valores.mean()
print(f'El promedio es: {promedio}')

El promedio es: 13.166666666666666

In [70]:
total = valores.sum()
total

np.int64(79)

In [71]:
maximo = valores.max()
maximo

np.int64(22)

In [72]:
min = valores.min()
min

np.int64(7)

In [74]:
# Crea una serie de Pandas con los días de la semana como índice  (asumiendo que el primer valor corresponde al Lunes).
ventas = [120, 150, 90, 200, 210, 130, 160]
indice_dias = pd.Series(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'])
indice_dias

0        lunes
1       martes
2    miercoles
3       jueves
4      viernes
5       sabado
6      domingo
dtype: object

In [75]:
serie_ventas = pd.Series(ventas, indice_dias)
serie_ventas

lunes        120
martes       150
miercoles     90
jueves       200
viernes      210
sabado       130
domingo      160
dtype: int64

In [76]:
suma_total_ventas = serie_ventas.sum()
suma_total_ventas

np.int64(1060)

In [77]:
dia_mayores_ventas = serie_ventas.max()
dia_mayores_ventas

np.int64(210)

In [78]:
promedio_ventas = serie_ventas.mean()
promedio_ventas

np.float64(151.42857142857142)

In [79]:
# Datos proporcionados
personas = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

personas_df = pd.DataFrame(personas)
filtro = personas_df['Edad'] >= 25
filtro

0     True
1     True
2    False
3     True
Name: Edad, dtype: bool

In [80]:
df_filtrado = personas_df[filtro]
df_filtrado

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
3   Sara    27     Bilbao

In [81]:
personas_df['Edad_en_10_año'] = personas_df['Edad'] + 10

In [82]:
personas_df['Es_Mayor_de_25 '] = personas_df['Edad'] > 25
personas_df

   Nombre  Edad     Ciudad  Edad_en_10_año  Es_Mayor_de_25
0     Ana    25     Madrid              35            False
1    Luis    30  Barcelona              40             True
2  Carlos    22   Valencia              32            False
3    Sara    27     Bilbao              37             True

In [83]:
ruta = 'Top-Películas.csv'
pelis_df = pd.read_csv(ruta)
pelis_df

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
...,...,...,...,...,...,...,...,...,...,...
2527,2527,998.0,The Invisible Man,James Whale,1933.0,71.0,Terror,7.6,87.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00

In [88]:
df_pelis_ord = pelis_df.sort_values(by='rating', ascending=False)
df_pelis_ord.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
5,5,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Drama,9.0,84.0,534.86
6,6,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Biografía,9.0,95.0,96.90
7,7,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Drama,9.0,95.0,96.90
8,8,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Historia,9.0,95.0,96.90
9,9,4.0,12 Angry Men,Sidney Lumet,1957.0,96.0,Crimen,9.0,97.0,4.36

In [90]:
df_pelis_ord = pelis_df.sort_values(by=['rating', 'recaudación(M)'], ascending=False)
df_pelis_ord.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
5,5,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Drama,9.0,84.0,534.86
11,11,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Acción,9.0,94.0,377.85
12,12,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Aventura,9.0,94.0,377.85
13,13,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Drama,9.0,94.0,377.85
6,6,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Biografía,9.0,95.0,96.90

In [91]:
df_pelis_agrupado = pelis_df.groupby('género')['rating'].mean()
df_pelis_agrupado

género
Acción             7.987255
Animación          7.943902
Aventura           7.980435
Biografía          7.971698
Ciencia Ficción    7.986567
Comedia            7.909910
Crimen             7.993500
Deportes           7.980000
Drama              7.980444
Familiar           7.932692
Fantasía           7.929508
Film-Noir          7.977273
Guerra             8.053191
Historia           7.931818
Misterio           7.991262
Musica             7.909677
Musical            7.943750
Romance            7.937398
Terror             7.875758
Thriller           7.929286
Western            8.006250
Name: rating, dtype: float64

In [94]:
pelis_prom_recaudo = pelis_df.groupby('año')['recaudación(M)'].sum()
pelis_prom_recaudo.sort_values(ascending=False).head(10)

año
2014.0    8015.90
2019.0    7092.95
2010.0    6899.96
2016.0    6860.23
2015.0    6817.12
2012.0    6487.22
2009.0    6486.34
2018.0    5992.02
2008.0    5603.30
2017.0    5381.90
Name: recaudación(M), dtype: float64

In [97]:
## Concatenar dos o mas DF
personas2 = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27]
})
personas3 = pd.DataFrame({
    'Nombre': ['Carmela', 'Max', 'Carlos', 'Laura'],
    'Edad': [27, 35, 28, 27]
})

In [98]:
personas_unidas = pd.merge(personas2, personas3, on="Nombre")
personas_unidas

   Nombre  Edad_x  Edad_y
0  Carlos      22      28

In [99]:
personas_unidas_inner = pd.merge(personas2, personas3, on="Nombre", how="inner")
personas_unidas_inner

   Nombre  Edad_x  Edad_y
0  Carlos      22      28

In [102]:
personas_concatenado = pd.concat([personas2, personas3])
personas_concatenado

    Nombre  Edad
0      Ana    25
1     Luis    30
2   Carlos    22
3     Sara    27
0  Carmela    27
1      Max    35
2   Carlos    28
3    Laura    27

In [103]:
personas_concatenado = pd.concat([personas2, personas3], axis=1)
personas_concatenado

   Nombre  Edad   Nombre  Edad
0     Ana    25  Carmela    27
1    Luis    30      Max    35
2  Carlos    22   Carlos    28
3    Sara    27    Laura    27

In [104]:
personas_concatenado = pd.concat([personas2, personas3], ignore_index=True)
personas_concatenado

    Nombre  Edad
0      Ana    25
1     Luis    30
2   Carlos    22
3     Sara    27
4  Carmela    27
5      Max    35
6   Carlos    28
7    Laura    27

In [106]:
personas_concatenado = pd.concat([personas2, personas3],keys=['personas2', 'personas3'])
personas_concatenado

              Nombre  Edad
personas2 0      Ana    25
          1     Luis    30
          2   Carlos    22
          3     Sara    27
personas3 0  Carmela    27
          1      Max    35
          2   Carlos    28
          3    Laura    27

## Fechas y Horas

In [109]:
fechas = pd.Series(pd.date_range('20260101', periods=6))
fechas

0   2026-01-01
1   2026-01-02
2   2026-01-03
3   2026-01-04
4   2026-01-05
5   2026-01-06
dtype: datetime64[ns]

In [111]:
type(fechas[0])

pandas._libs.tslibs.timestamps.Timestamp

In [112]:
fechas = pd.Series(pd.date_range('20260101', periods=6, freq='D'))
fechas

0   2026-01-01
1   2026-01-02
2   2026-01-03
3   2026-01-04
4   2026-01-05
5   2026-01-06
dtype: datetime64[ns]

In [113]:
fechas = pd.Series(pd.date_range('20260101', periods=6, freq='5D'))
fechas

0   2026-01-01
1   2026-01-06
2   2026-01-11
3   2026-01-16
4   2026-01-21
5   2026-01-26
dtype: datetime64[ns]

In [115]:
ruta = 'Mercado+de+Valores+España.csv'
mercado = pd.read_csv(ruta)
mercado

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,02/01/2019,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,03/01/2019,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,04/01/2019,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,07/01/2019,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,08/01/2019,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,09/12/2019,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,10/12/2019,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,11/12/2019,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,12/12/2019,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,13/12/2019,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [116]:
mercado['Fecha'][0]

'02/01/2019'

In [117]:
type(mercado['Fecha'][0])

str

In [146]:
mercado['Fecha'] = pd.to_datetime(mercado['Fecha'], format="%d-%m-%Y %H:%M")
mercado

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,2019-01-02,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,2019-01-03,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,2019-01-04,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,2019-01-07,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,2019-01-08,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,2019-12-09,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,2019-12-10,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,2019-12-11,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,2019-12-12,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,2019-12-13,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [127]:
mercado['Fecha'][0]

Timestamp('2019-01-02 00:00:00')

In [130]:
mercado['Fecha'][3].month

1

In [131]:
mercado.loc[0]

Ticker                        ANA
Fecha         2019-01-02 00:00:00
Cierre                       74.8
Referencia                   73.9
Volumen                    156300
Rotacion              11621188.98
Ultimo                       74.8
Alto                        75.16
Bajo                        72.38
Promedio                  74.3518
Name: 0, dtype: object

In [132]:
mercado.loc[0:2]

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,2019-01-02,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,2019-01-03,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,2019-01-04,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162

In [139]:
mercado.loc[mercado['Cierre']>176]

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
851,AENA,2019-06-18,177.60,172.95,297550,52314536.10,177.60,178.55,172.70,177.1890
852,AENA,2019-06-19,178.05,177.60,127424,22731097.55,178.05,179.90,177.85,178.3895
853,AENA,2019-06-20,176.50,178.05,239421,42301459.35,176.50,179.30,176.05,176.7072
855,AENA,2019-06-24,177.35,175.10,187741,33203306.45,177.35,177.35,175.60,176.9269
856,AENA,2019-06-25,177.30,177.35,145770,25799582.28,177.30,177.55,175.85,177.0805
861,AENA,2019-07-02,176.25,174.60,185151,32673982.97,176.25,177.65,175.75,176.4489
862,AENA,2019-07-03,177.15,176.25,134073,23808922.10,177.15,179.35,176.85,177.5235
863,AENA,2019-07-04,177.55,177.15,240062,42584849.85,177.55,177.95,177.00,177.4903

In [140]:
mercado[mercado['Cierre']>176]

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
851,AENA,2019-06-18,177.60,172.95,297550,52314536.10,177.60,178.55,172.70,177.1890
852,AENA,2019-06-19,178.05,177.60,127424,22731097.55,178.05,179.90,177.85,178.3895
853,AENA,2019-06-20,176.50,178.05,239421,42301459.35,176.50,179.30,176.05,176.7072
855,AENA,2019-06-24,177.35,175.10,187741,33203306.45,177.35,177.35,175.60,176.9269
856,AENA,2019-06-25,177.30,177.35,145770,25799582.28,177.30,177.55,175.85,177.0805
861,AENA,2019-07-02,176.25,174.60,185151,32673982.97,176.25,177.65,175.75,176.4489
862,AENA,2019-07-03,177.15,176.25,134073,23808922.10,177.15,179.35,176.85,177.5235
863,AENA,2019-07-04,177.55,177.15,240062,42584849.85,177.55,177.95,177.00,177.4903

In [158]:
mayores_fechas = mercado['Fecha']
type(mayores_fechas[0])

pandas._libs.tslibs.timestamps.Timestamp

In [160]:
type(mercado['Fecha'])

pandas.core.series.Series

In [162]:
meses = []
for m in mercado['Fecha']:
    meses.append(m.year)

meses

[2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 2019,
 ...]

In [154]:
agrupados = mercado['Cierre'].max()
print(agrupados)

178.05